FROM ubuntu:20.04
RUN apt-get update
RUN apt-get install -y python3-pip
RUN pip3 install requests
RUN pip3 install Flask
RUN pip3 install numpy==1.21.5
RUN pip3 install sklearn
COPY WrapperClass.py /
COPY titanic_model.pkl /
CMD python3 WrapperClass.py